Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2022
Var
// Seção de Declarações das variáveis 
   procedimento soma (a : real; b : real)
   inicio
   escreva(a,"+",b,"=",(a + b))
   fimprocedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    soma(1,2)

Fimalgoritmo